name: Reconcile GitHub Issue

on:
  issues:
    types:
      - opened
      - edited
      - closed
      - reopened
      - labeled
      - unlabeled

# This prevents potential race conditions by only allowing this action to handle
# one update at a time for a given issue.
concurrency:
  group: reconcile-issue-${{ github.event.issue.number }}
  cancel-in-progress: true

jobs:
  reconcile-issue:
    permissions:
      contents: write
      issues: write
      pull-requests: write
    uses: konveyor/release-tools/.github/workflows/reconcile-issue.yaml@main
